// Centralized VoidManager schema constants. All table/column names and enum values
// live here only (per CLAUDE.md). Fail loudly elsewhere on missing columns.

/**
 * The six approval status values, in display order.
 *
 * CRITICAL: case-sensitive, lowercase with spaces. These must match the VoidManager
 * Revit add-in / VmoViewer exactly, or edits written back to the .db won't be recognized.
 */
export const APPROVAL_STATUSES = [
  'concept',
  'open for review',
  'approved',
  'rejected',
  'released for execution',
  'executed',
] as const;

export type ApprovalStatus = (typeof APPROVAL_STATUSES)[number];

export function isApprovalStatus(value: string): value is ApprovalStatus {
  return (APPROVAL_STATUSES as readonly string[]).includes(value);
}

// --- Real VoidManager DB schema (see docs/SCHEMA_FINDINGS.md) ---
// The DB is a dictionary-encoded, mutation-versioned object store. Every entity column is an INT
// foreign key into a D_<Type> dictionary table (literal in `Value`) or another entity table.
// Resolution + current-version filtering happens in LocalDbRepository, not here.

/** Entity (object) tables. */
export const TABLE = {
  voidCircle: 'VoidCircle',
  voidRectangle: 'VoidRectangle',
  story: 'Story',
  building: 'Building',
  project: 'Project',
  user: 'User',
  point3D: 'Point3D',
  vector3D: 'Vector3D',
  hostElementSuper: 'HostElementSuper',
  superSubHostIntersection: 'SuperSubHostIntersection',
} as const;

/** Dictionary tables: `(ID INTEGER PK, Value <typed> UNIQUE)`. */
export const DICT = {
  boolean: 'D_Boolean',
  statusOfApproval: 'D_StatusOfApproval',
  sequenceName: 'D_SequenceName',
  category: 'D_Category',
  emailAddress: 'D_EmailAddress',
  name: 'D_Name',
  model: 'D_Model',
  guid: 'D_GUID',
  /** X, Y, Z coordinates (Point3D/Vector3D) and Story.Elevation — Revit internal mm (signed). */
  numericOneDecimal: 'D_NumericOneDecimal',
  /**
   * Unsigned sizes: Diameter, Width, Height, Thickness, Tolerance*, ElevationFromStory.
   * Confirmed by AttributeDimensionTable (DB-resident mapping) and plausible mm values.
   */
  numericOneDecimalUnsigned: 'D_NumericOneDecimalUnsigned',
  /** Level index (integer). */
  numericInteger: 'D_NumericInteger',
  timestampUtc: 'D_TimestampUtc',
  notes: 'D_Notes',
} as const;

/**
 * D_Boolean encoding.
 *
 * D_Boolean.ID=1 → Value=1 (bit true)  → "true"
 * D_Boolean.ID=2 → Value=0 (bit false) → "false"
 *
 * NOTE: In VoidCircle / VoidRectangle ALL rows currently have IsValid=2 (false).
 * The "current version" of a void is NOT found via IsValid but via MAX(ID) per ExternalId.
 * Other entity tables (Story, Building, Project, User, HostElementSuper, …) use IsValid=1 normally.
 */
export const DB_BOOLEAN = { true: 1, false: 2 } as const;

/** Shared void columns (INT refs). VoidRectangle adds Width/Height/Tolerance{Above,Right,Below,Left}. */
export const VOID_COLUMNS = [
  'ID',
  'HostId',
  'IsValid',
  'CreatedOn',
  'CreatedBy',
  'IsClosed',
  'Notes',
  'Thickness',
  'ExternalId',
  'AssignedTo',
  'StatusOfApproval',
  'Location',
  'Direction',
  'SequenceName',
  'MergedIntoVoidId',
  'IsAutogenerated',
] as const;
